"""empty message

Revision ID: a00e74707c45
Revises: ecac65dfdfac
Create Date: 2019-07-03 18:43:10.036011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a00e74707c45'
down_revision = 'ecac65dfdfac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('cat_type', sa.String(length=30), nullable=False))
    op.drop_column('categories', 'is_income')
    op.alter_column('operations', 'op_type',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operations', 'op_type',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.add_column('categories', sa.Column('is_income', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('categories', 'cat_type')
    # ### end Alembic commands ###
