"""empty message

Revision ID: ecac65dfdfac
Revises: 2ead040c5d99
Create Date: 2019-07-03 18:13:13.668895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecac65dfdfac'
down_revision = '2ead040c5d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_ibfk_1', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('operations', sa.Column('op_type', sa.String(length=30), nullable=True))
    op.drop_constraint('operations_ibfk_1', 'operations', type_='foreignkey')
    op.drop_constraint('operations_ibfk_2', 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'operations', 'wallets', ['wallet_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('operations', 'is_income')
    op.drop_constraint('wallets_ibfk_1', 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key('wallets_ibfk_1', 'wallets', 'users', ['user_id'], ['id'])
    op.add_column('operations', sa.Column('is_income', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key('operations_ibfk_2', 'operations', 'wallets', ['wallet_id'], ['id'])
    op.create_foreign_key('operations_ibfk_1', 'operations', 'categories', ['category_id'], ['id'])
    op.drop_column('operations', 'op_type')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_ibfk_1', 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
